const en = [
    {
      key: '`',
      key2: 'ё',
      nameShift2: 'Ё',
      nameShift: '~',
      code: 'Backquote',
    },
    {
      key: '1',
      nameShift: '!',
      key2: '1',
      nameShift2: '!',
      code: 'Digit1',
    },
    {
      key: '2',
      nameShift: '@',
      key2: '2',
      nameShift2: '"',
      code: 'Digit2',
    },
    {
      key: '3',
      nameShift: '#',
      key2: '3',
      nameShift2: '№',
      code: 'Digit3',
    },
    {
      key: '4',
      nameShift: '$',
      key2: '4',
      nameShift2: ';',
      code: 'Digit4',
    },
    {
      key: '5',
      nameShift: '%',
      key2: '5',
      nameShift2: '%',
      code: 'Digit5',
    },
    {
      key: '6',
      nameShift: '^',
      key2: '6',
      nameShift2: ':',
      code: 'Digit6',
    },
    {
      key: '7',
      nameShift: '&',
      key2: '7',
      nameShift2: '?',
      code: 'Digit7',
    },
    {
      key: '8',
      nameShift: '*',
      key2: '8',
      nameShift2: '*',
      code: 'Digit8',
    },
    {
      key: '9',
      nameShift: '(',
      key2: '9',
      nameShift2: '(',
      code: 'Digit9',
    },
    {
      key: '0',
      nameShift: ')',
      key2: '0',
      nameShift2: ')',
      code: 'Digit0',
    },
    {
      key: '-',
      nameShift: '_',
      key2: '-',
      nameShift2: '_',
      code: 'NumpadSubtract',
    },
    {
      key: '=',
      nameShift: '+',
      key2: '=',
      nameShift2: '+',
      code: 'Equal',
    },
    {
      key: 'Backspace',
      nameShift: 'Backspace',
      key2: 'Backspace',
      nameShift2: 'Backspace',
      code: 'Backspace',
    },
    {
      key: 'Tab',
      nameShift: 'Tab',
      key2: 'Tab',
      nameShift2: 'Tab',
      code: 'Tab',
    },
    {
      key: 'q',
      key2: 'й',
      nameShift2: 'Й',
      nameShift: 'Q',
      code: 'KeyQ',
    },
    {
      key: 'w',
      key2: 'ц',
      nameShift2: 'Ц',      
      nameShift: 'W',        
      code: 'KeyW',      
    },
    {
      key: 'e',     
      nameShift: 'E',
      key2: 'у',
      nameShift2: 'У',      
      code: 'KeyE',      
    },
    {
      key: 'r',      
      nameShift: 'R',
      key2: 'к',
      nameShift2: 'К',       
      code: 'KeyR',       
    },
    {
      key: 't',       
      nameShift: 'T',
      key2: 'е',
      nameShift2: 'Е',     
      code: 'KeyT',       
    },
    {
      key: 'y',     
      nameShift: 'Y',
      key2: 'н',
      nameShift2: 'Н',       
      code: 'KeyY',
    },
    {
      key: 'u',       
      nameShift: 'U',        
      code: 'KeyU',
      key2: 'г',
      nameShift2: 'Г',        
    },
    {
      key: 'i',       
      nameShift: 'I',
      key2: 'ш',
      nameShift2: 'Ш',      
      code: 'KeyI',      
    },
    {
      key: 'o',      
      nameShift: 'O',
      key2: 'щ',
      nameShift2: 'Щ',      
      code: 'KeyO',      
    },
    {
      key: 'p',    
      nameShift: 'P',
      key2: 'з',
      nameShift2: 'З',       
      code: 'KeyP',      
    },
    {
      key: '[',      
      nameShift: '{',
      key2: 'х',
      nameShift2: 'Х',     
      code: 'BracketLeft',       
    },
    {
      key: ']',      
      nameShift: '}',
      key2: 'ъ',
      nameShift2: 'Ъ',       
      code: 'BracketRight',       
    },
    {
      key: '\\',       
      nameShift: '|',
      key2: '\\',
      nameShift2: '/',      
      code: 'Backslash',      
    },
    {
      key: 'Delete',       
      nameShift: 'Delete',
      key2: 'Delete',
      nameShift2: 'Delete',      
      code: 'Delete',        
    },
    {
      key: 'CapsLock',       
      nameShift: 'CapsLock',
      key2: 'CapsLock',
      nameShift2: 'CapsLock',        
      code: 'CapsLock',              
    },
    {
      key: 'a',      
      nameShift: 'A',
      key2: 'ф',
      nameShift2: 'Ф',      
      code: 'KeyA',       
    },
    {
      key: 's',      
      nameShift: 'S',
      key2: 'ы',
      nameShift2: 'Ы',       
      code: 'KeyS',       
    },
    {
      key: 'd',       
      nameShift: 'D',
      key2: 'в',
      nameShift2: 'В',       
      code: 'KeyD',       
    },
    {
      key: 'f',       
      nameShift: 'F',
      key2: 'а',
      nameShift2: 'А',       
      code: 'KeyF',       
    },
    {
      key: 'g',
      nameShift: 'G',
      key2: 'п',
      nameShift2: 'П',
      code: 'KeyG',
    },
    {
      key: 'h',
      nameShift: 'H',
      key2: 'р',
      nameShift2: 'Р',
      code: 'KeyH',
    },
    {
      key: 'j',
      nameShift: 'J',
      key2: 'о',
      nameShift2: 'О',
      code: 'KeyJ',
    },
    {
      key: 'k',
      nameShift: 'K',
      key2: 'л',
      nameShift2: 'Л',
      code: 'KeyK',
    },
    {
      key: 'l',
      nameShift: 'L',
      key2: 'д',
      nameShift2: 'Д',
      code: 'KeyL',
    },
    {
      key: ';',
      nameShift: ':',
      key2: 'ж',
      nameShift2: 'Ж',
      code: 'Semicolon',
    },
    {
      key: "'",
      nameShift: '',
      key2: 'э',
      nameShift2: 'Э',
      code: 'Quote',
    },
    {
      key: 'Enter',
      nameShift: 'Enter',
      key2: 'Enter',
      nameShift2: 'Enter',
      code: 'Enter',
    },
    {
      key: 'Shift',
      nameShift: 'Shift',
      key2: 'Shift',
      nameShift2: 'Shift',
      code: 'ShiftLeft',
    },
    {
      key: 'z',
      nameShift: 'Z',
      key2: 'я',
      nameShift2: 'Я',
      code: 'KeyZ',
    },
    {
      key: 'x',
      nameShift: 'X',
      key2: 'ч',
      nameShift2: 'Ч',
      code: 'KeyX',
    },
    {
      key: 'c',
      nameShift: 'C',
      key2: 'c',
      nameShift2: 'C',
      code: 'KeyC',
    },
    {
      key: 'v',
      nameShift: 'V',
      key2: 'м',
      nameShift2: 'М',
      code: 'KeyV',
    },
    {
      key: 'b',
      nameShift: 'B',
      key2: 'и',
      nameShift2: 'И',
      code: 'KeyB',
    },
    {
      key: 'n',
      nameShift: 'N',
      key2: 'т',
      nameShift2: 'Т',
      code: 'KeyN',
    },
    {
      key: 'm',
      nameShift: 'M',
      key2: 'ь',
      nameShift2: 'Ь',
      code: 'KeyM',
    },
    {
      key: ',',
      nameShift: '<',
      key2: 'б',
      nameShift2: 'Б',
      code: 'Comma',
    },
    {
      key: '.',
      nameShift: '>',
      key2: 'ю',
      nameShift2: 'Ю',
      code: 'Period',
    },
    {
      key: '/',
      nameShift: '?',
      key2: '.',
      nameShift2: ',',
      code: 'Slash',
    },
    {
      key: '▲',
      nameShift: '▲',
      key2: '▲',
      nameShift2: '▲',
      code: 'ArrowUp',
    },
    {
      key: 'Shift',
      nameShift: 'Shift',
      key2: 'Shift',
      nameShift2: 'Shift',
      code: 'ShiftRight',
    },
    {
      key: 'Ctrl',
      nameShift: 'Ctrl',
      key2: 'Ctrl',
      nameShift2: 'Ctrl',
      code: 'ControlLeft',
    },
    {
      key: 'Win',
      nameShift: 'Win',
      key2: 'Win',
      nameShift2: 'Win',
      code: 'MetaLeft',
    },
    {
      key: 'Alt',
      nameShift: 'Alt',
      key2: 'Alt',
      nameShift2: 'Alt',
      code: 'AltLeft',
    },
    {
      key: ' ',
      nameShift: ' ',
      key2: ' ',
      nameShift2: ' ',
      code: 'Space',
    },
    {
      key: 'Alt',
      nameShift: 'Alt',
      key2: 'Alt',
      nameShift2: 'Alt',
      code: 'AltRight',
    },
    {
      key: '◄',
      nameShift: '◄',
      key2: '◄',
      nameShift2: '◄',
      code: 'ArrowLeft',
    },
    {
      key: '▼',
      nameShift: '▼',
      key2: '▼',
      nameShift2: '▼',
      code: 'ArrowDown',
    },
    {
      key: '►',
      nameShift: '►',
      key2: '►',
      nameShift2: '►',
      code: 'ArrowRight',
    },
    {
      key: 'Ctrl',
      nameShift: 'Ctrl',
      key2: 'Ctrl',
      nameShift2: 'Ctrl',
      code: 'ControlRight',
    },
];
export default en;